### ISSUE TITLE
https protocol only used for submodules in gh-pages branch

### ISSUE THREAD

**Issue by aspiers** [fghaas/presentation-template#14]
Is there any particular reason you excluded 07435b4c9a27d67454272e962e217e1197d28469 from `master`?  I know it's probably not technically needed in `master`, but now that other people are using this, I think it's better if the differences between `master` and `gh-pages` are minimised, because there's a good chance people will do stuff like

```
git push github master:gh-pages
```

So unless there's a good reason not to use `https` for submodules in `master`, I think it's worth cherry-picking that commit.

**Comment by fghaas** [comment]
The only reason I use `git://` URLs in master is that they're usually faster to clone, which comes in handy if we're dealing with complex or large repos as submodules.

**Comment by aspiers** [comment]
Oh, interesting.  Do you really notice the difference though?  All these repos clone in seconds for me.  Maybe that's just my fibre connection? :)

**Comment by fghaas** [comment]
https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols does indicate that the git protocol is expected to be faster, though GitHub have probably optimized their HTTPS servers to the hilt too.
