### ISSUE TITLE
dubious recommendation to fork repo?

### ISSUE THREAD

**Issue by aspiers** [fghaas/presentation-template#15]
The problem with forking this template repo on github is that AFAIK, github only lets you have one fork per upstream repo.  So it's fine the first time, but then after that, you can't fork for any further presentations - right?  If so, it might be better to advise users to click the plus icon to create a new repo, then add yours as a remote and fetch from it to get a starting point.  Thoughts?

**Comment by fghaas** [comment]
Anyone _already_ familiar with GitHub will know that. For anyone _not_ that familiar with GitHub, I would prefer them to use an actual fork at least to start with — gives me an idea of how popular/useful this repo is.

**Comment by aspiers** [comment]
Actually I suspect most GitHub users don't know that, because it's very rare that anyone would need to try to make multiple forks of the same repo.

**Comment by aspiers** [comment]
OTOH, I agree that it would be nice to track popularity via the fork network ...

**Comment by fghaas** [comment]
I'd prefer to keep encouraging people to fork. If they create multiple presentations they'll figure out they'll need to just fire up their own repo, and push to that.

Also, on second thought the idea that people would like to fork _this_ repo more than once is a bit silly: you might fork this one once, but then you'll build your own template on top of it, and base your future work on that.
