### ISSUE TITLE
Keyboard shortcut cheatsheet is unreadable

### ISSUE THREAD

**Issue by aspiers** [fghaas/presentation-template#5]
After pressing `?` to get the keyboard shortcut cheatsheet, all the text in the table is black-on-black, so unreadable unless you select it.

**Comment by fghaas** [comment]
I never even knew such a thing existed, much less that it had a key binding.

**Comment by aspiers** [comment]
Yeah, it's a nice feature :-)

**Comment by fghaas** [comment]
Its CSS class seems to be named `overlay`, so that's the one where the foreground `color` probably needs to be set to `white`.

**Comment by aspiers** [comment]
Just occurred to me that whilst fixing this, we should mention the `?` key in the README.

**Comment by aspiers** [comment]
Here's my fix for the SUSE theme:

https://github.com/aspiers/presentation-template/commit/38fd67fa30ee90ac06c52d57e4c834c05d1ac5a9

but you can't use it until you merge #13 (and even then it references a SUSE colour).

**Comment by fghaas** [comment]
Updated (using white, not green, for the foreground colo[u]?r). Thanks!
