### ISSUE TITLE
support for asciinema?

### ISSUE THREAD

**Issue by aspiers** [fghaas/presentation-template#6]
Since this is a somewhat opinionated template, why not load it up with all the goodies?  asciinema is an obvious example.  The fact that I need it for my next presentation is uhh, purely coincidental.

**Comment by fghaas** [comment]
I wonder what's a good generic way to include asciinema. Obvious choice would be to include the integration script in index.html, but I don't know how often that changes upstream, and that JavaScript seems not to be available as a submodule. Ideas?

**Comment by aspiers** [comment]
Not sure, since I haven't gone through the process of using it myself yet.  But if I do, I'll put ideas here :-)

**Comment by fghaas** [comment]
Note to self, this is the JavaScript code that asciinema.org generates, after putting it through a JavaScript beautifier:

``` javascript
! function() {
    function e(e, t) {
        e.parentNode.insertBefore(t, e.nextSibling)
    }

    function t(e, t) {
        function i(e) {
            var i = t.getAttribute("data-" + e);
            return i ? e + "=" + i : void 0
        }
        var a = ["size", "speed", "autoplay", "loop", "theme", "t"];
        return "?" + a.map(i).filter(Boolean).join("&")
    }

    function i(e) {
        var t = document.createElement("a");
        return t.href = e, t
    }

    function a(e) {
        var t = i(e.src);
        return t.protocol + "//" + t.host
    }

    function n(i) {
        function n(e) {
            if (e.origin === s) {
                var t = e.data[0],
                    i = e.data[1],
                    a = c.contentWindow || c;
                e.source == a && "asciicast:size" == t && (c.style.width = "" + i.width + "px", c.style.height = "" + i.height + "px")
            }
        }
        if (!i.dataset.player) {
            var s = a(i),
                l = s + "/api",
                r = i.id.split("-")[1],
                o = document.createElement("div");
            o.id = "asciicast-container-" + r, o.className = "asciicast", o.style.display = "block", o.style.float = "none", o.style.overflow = "hidden", o.style.padding = 0, o.style.margin = "20px 0", e(i, o);
            var c = document.createElement("iframe");
            c.src = l + "/asciicasts/" + r + t(o, i), c.id = "asciicast-iframe-" + r, c.name = "asciicast-iframe-" + r, c.scrolling = "no", c.setAttribute("allowFullScreen", "true"), c.style.overflow = "hidden", c.style.margin = 0, c.style.border = 0, c.style.display = "inline-block", c.style.width = "100%", c.style.float = "none", c.style.visibility = "hidden", c.onload = function() {
                this.style.visibility = "visible"
            }, o.appendChild(c), window.addEventListener("message", n, !1), i.dataset.player = o
        }
    }
    var s = document.querySelectorAll("script[id^='asciicast-']");
    [].forEach.call(s, n)
}();
```

**Comment by aspiers** [comment]
Hmm, code beautifiers still have a way to go ;-)  As the saying goes, you can't polish a turd ... although perhaps I'm being a little harsh given that it was clearly minified ;-)

**Comment by fghaas** [comment]
Well, I don't really want to copy this into my presentation template, not least because the asciinema-generated JS may change. Just copying the asciicast embed link doesn't work very nicely in Markdown though. I'm considering suggesting this:
- Add the asciinema embed script to the bottom of index.html, _without_ the `id` attribute:

``` html
<script type="text/javascript" src="https://asciinema.org/a/13104.js" async></script>
```
- Add just the script placeholder where you want the player to appear:

``` markdown
# Some title
<script id="asciicast-13104"></script>
```

Neither of the two are very elegant though. Any better ideas?

**Comment by aspiers** [comment]
What's not elegant about the second one?  Looks fine to me.

**Comment by fghaas** [comment]
Except it doesn't seem to work. :/ Will have to come back to this one.

**Comment by fghaas** [comment]
Closing this issue as I am about to archive this repo. https://github.com/asciinema/asciinema-server/pull/251 covers the use case. There is also https://github.com/jfx2006/reveal-asciinema which has, however, also been archived by its author.
